name: Build Jenkins AMI

on:
  push:
    branches:
      - main  # Triggers the workflow on a push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The build runs on the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This action checks out your repository so the workflow can access the code

      - name: Set up Packer
        uses: hashicorp/setup-packer@v1  # This action sets up Packer in the workflow environment

      - name: Run Packer build
        run: |
          packer build \
            -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            packer.json  # This command runs the Packer build using the JSON file and the AWS credentials stored in GitHub secrets